### PR TITLE
Allow modifications to CSP

### PR DESCRIPTION
**Pull request by Caged**
I've had a couple of situations where I've needed to modify the CSP directives.  Recently I needed to add a `fontSrc` directive to allow for loading local, custom fonts.  This PR adds a default `fontSrc` of `self` and also allows you to pass in a `cspDirectives` option which will let you customize any of the default CSP directives.  

LMK if you'd prefer a different approach or naming.  Also happy to document this.

/cc @josh

### CODE REVIEW

**Comment by Caged** [comment]
@josh I don't have write access, so it doesn't look like I can merge this.  Can you merge and release a new version when you get a moment?  Thanks!

**Comment by Caged** [comment]
@josh can you publish the new version on npm please?  🙏

**Comment by josh** [comment]
It should be—did I accidently publish the wrong version? It should be `0.8.0`.

**Comment by Caged** [comment]
Looks good this morning, but was < 0.8.0 when I pulled yesterday.  Maybe it took a moment for NPM to update.  Thanks!

**Comment by josh** [comment]
> Maybe it took a moment for NPM to update.

Ah--I've noticed the same a few times. Their resque might get backlogged too 😬

**Pull request merged**
